"""
--------------------------------------------------------
IFDSF Research Prototype
Module : optimization_agent.py

Purpose:
Optimization Agent

Consumes recommendations generated by the
Decision Support Engine and prepares them
for the IFDSF Orchestrator.

Author : Ajay Kumar
M.Tech (Data Science & AI)
IIIT Dharwad
--------------------------------------------------------
"""

import os
import pandas as pd


class OptimizationAgent:

    def __init__(self):

        self.agent_name = "Optimization Agent"

        self.result_file = "/content/drive/MyDrive/IFDSF_Data/outputs/optimization_results.csv"

    # -------------------------------------------------

    def load_decision(self):

        if not os.path.exists(self.result_file):

            raise FileNotFoundError(
                "Run optimization_model.py first."
            )

        return pd.read_csv(self.result_file)

    # -------------------------------------------------

    def run(self):

        print("\n" + "=" * 60)
        print(f"Running {self.agent_name}")
        print("=" * 60)

        decision = self.load_decision()

        recommendation = decision.iloc[0]["Recommendation"]

        risk = decision.iloc[0]["Risk Level"]

        confidence = decision.iloc[0]["Confidence (%)"]

        print("\nDecision Recommendation")

        print("-----------------------")

        print(f"Recommendation : {recommendation}")

        print(f"Risk Level     : {risk}")

        print(f"Confidence     : {confidence}%")

        response = {

            "agent": self.agent_name,

            "recommendation": recommendation,

            "risk": risk,

            "confidence": float(confidence),

            "status": "SUCCESS"

        }

        print("\nOptimization Agent Completed Successfully.")

        return response


# --------------------------------------------------------

if __name__ == "__main__":

    agent = OptimizationAgent()

    result = agent.run()

    print("\nReturned Object")

    print(result)
