"""
--------------------------------------------------------
IFDSF Research Prototype
Module : optimization_agent.py

Purpose:
Optimization Agent responsible for reading
decision recommendations generated by the
Decision Support Engine.

Author : Ajay Kumar
M.Tech (Data Science & AI)
IIIT Dharwad
--------------------------------------------------------
"""

import os
import pandas as pd


class OptimizationAgent:

    def __init__(self):

        self.name = "Optimization Agent"

        self.file = "/content/drive/MyDrive/IFDSF_Data/outputs/optimization_results.csv"

    # -------------------------------------------------

    def run(self):

        print("=" * 60)
        print(f"Running {self.name}")
        print("=" * 60)

        if not os.path.exists(self.file):

            print("Optimization result not found.")

            return None

        decision = pd.read_csv(self.file)

        print("\nDecision Recommendation\n")

        print(decision)

        response = {

            "agent": self.name,

            "recommendation": decision.iloc[0]["Recommendation"],

            "risk": decision.iloc[0]["Risk Level"],

            "confidence": float(decision.iloc[0]["Confidence (%)"]),

            "status": "SUCCESS"

        }

        print("\nOptimization Agent Completed Successfully.")

        return response


if __name__ == "__main__":

    agent = OptimizationAgent()

    print(agent.run())
